# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Run on environment'
        required: true
        type: string
        default: 'default value'
        
      branch:
        description: 'Select the branch'
        required: true
        type: choice
        default: develop-branch
        options:
          - develop-branch
          - test-branch
      notify:
        description: 'receive notify when workflow is completed'
        required: false
        type: boolean
  schedule:
    - cron: '*/10 * * * *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.5.0
        with: 
            node-version: 10.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Runs a single command using the runners shell
      - name: Run a target_environment
        run: echo "${{ inputs.target_environment }}"
      - name: Run a branch
        run: echo "${{ inputs.branch }}"
      - name: Run a notify
        run: echo "${{ inputs.notify }}"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: build artifact
          path: dist
